version: "1"

services:
  chatbot_interface:
    container_name: chatbot_interface
    build:
      context: ./chatbot_interface
      dockerfile: Dockerfile
    ports:
      - ${CHATBOT_INTERFACE_PORT}:3000
    env_file:
      - .env
    image: chatbot_interface:latest
    depends_on:
      - chatbot_api
    networks:
      goal_parser_network:
        ipv4_address: ${CHATBOT_INTERFACE_IP}

  chatbot_api:
    container_name: chatbot_api
    build:
      context: ./chatbot_api
      dockerfile: Dockerfile
    ports:
      - ${CHATBOT_API_PORT}:5000
    image: chatbot_api:latest
    networks:
      goal_parser_network:
        ipv4_address: ${CHATBOT_API_IP}

networks:
  goal_parser_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${SUBNET}